### ISSUE TITLE
v2.00 c-array not correct on one- & two color pictures

### ISSUE THREAD

**Issue by esprit1711** [Pconti31/GUIslice_Image2C#5]
hey. I found a bug in v2.00 when i try to create a c-array from a picture with 1 or 2 Colors. The generated C-Array looks good in GUISlice Builder, but the Arduino IDE is not able to compile this code, because of the first few rows in the array:
`const unsigned char Settings_icon[2500+5] = {`
`0x00, // Height of image`
`0x32,`
`0x00, // Width of image`
`0x32,`
`000, // red color`
`093, // green color`
`181, // blue color`

because of the number format, the decimal numbers for red and green will be interpreted as octal numbers.
Even when i change this manualy, the array is still broken. after loading the picture i can see some random pixels and my ESP32 just crash and restart.

to Avoid this problem, i can use the V1.04 of Image2C or change one Random Pixel in the Picture to force the V2.00 to interprete the picture as 3 Color Picture and generate a C-array in a different format.
in both cases, the picture in GUISlice Builder can not be transparent anymore, i always have the pink array, which indicate the transparent area. I have attach my test pictures (1 color Transparent/blue and 3 color Transparent/blue/1Pixel_different_blue) and the generated C-arrays
[Settings_icon.zip](https://github.com/Pconti31/GUIslice_Image2C/files/8784708/Settings_icon.zip)

**Comment by Pconti31** [comment]
@esprit1711 Yes, I screwed up with the octal. 

Thanks for the info. I'll debug this and post a new version when I figure out what is going wrong.
Paul--

**Comment by esprit1711** [comment]
thank you for your fast response :)
i have add the `bmap_base++;` line in GUIslice_drv_tft_espi.cpp but it still crash. I thought i miss something, but because of your edit i think you also tried it.

EDIT: i found the Solution for this Problem. Your Image2C Software works perfekt (except of the octal numbers, which should be decimal). I have to change the Parameter "Image Format" for my Image Button in GUIslicer Builder. Its default setting was "GSLC_IMGREF_FMT_BMP24". After i change this to "GSLC_IMGREF_FMT_RAW1" (and the modification from octal to decimal numbers in the c-array header) the ESP32 did not crash anymore, but the Image was shifted. I removed the `bmap_base++;` line from your fix and now it looks and work perfekt^^

**Comment by Pconti31** [comment]
@esprit1711 I just posted the fixes in release 2.01

There were a couple of problems but easy to fix.

I also added more information to the readme for guidence on using the Builder and GUIslice API.

Also my fix is removing the extra bmap_base++ not adding it.  Not sure why you thought it was to be added.
Anyway, very happy you got things working.
Thanks again.!
Paul--

**Comment by esprit1711** [comment]
oh, sometimes i am just stupid :D . i saw what you change for the fix and thaught you have add the extra bmap_base++ cause i have missintereprete the comparison from github.
I am very impressed how fast you have fixed the problem. thank you very much!
